[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  olikraus/U8g2
  bblanchon/ArduinoJson@^7
  miguelbalboa/MFRC522@^1.4.11
  https://github.com/Seeed-Studio/PN532.git#arduino
build_flags =
  -DCORE_DEBUG_LEVEL=0
  -DNFC_INTERFACE_HSU
