blank_issues_enabled: true
contact_links:
  - name: Sicherheitslücke
    url: https://github.com/christiankohrn/opentakt-zeit/security/advisories/new
    about: Bitte keine öffentlichen Issues für Sicherheitsprobleme.
